config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, :scope => [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path(@lists), status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Submit comment", class: "btn btn-primary" %>
<% end %>
<p> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>My Lists</h1>
<%@lists.each do |list|%>
<li><%= link_to list.name, list_path(list) %></li>
<%end%>
<p> </p>
<%= link_to "Create new list", 'lists/new'%>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Submit list", class: "btn btn-primary" %>
<% end %>

<%= link_to "Go to home page", 'lists/index'%>

app/views/lists/show.html.erb
<h1>List's details</h1>

<p style="color: green"><%= notice %></p>
<p><strong>Bookmarks</strong></p>
<ul class="list-group">
  <% @list.bookmarks.each do |bookmark| %>
    <li class="list-group-item">
      <strong> <%= "Title:" %> </strong><%=   bookmark.movie.title %>
    </li>
    <li class="list-group-item">
      <strong> <%= "Overview:" %> </strong><%=   bookmark.movie.overview %>
    </li>
    <li class="list-group-item">
      <strong> <%= "Rating:" %> </strong><%=   bookmark.movie.rating %>
    </li>
    <li>
      <strong> <%= "Comment:" %> </strong> <%= bookmark.comment %>
      <%= link_to "Delete",
        bookmark_path(bookmark),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
      %>
    </li>
  <% end %>
</ul>
<br>
<div>
  <%= link_to "Back to lists", lists_path %>
  <%= link_to "Add bookmark", new_list_bookmark_path(@list) %> |
  <%= button_to "Destroy this list", @list, method: :delete %>
</div>